mytutz/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.views import homepage, pre_registration, complete_registration, verify_email, user_login, user_logout, \
                            get_faculty_options, get_department_options, pre_forgot_password, forgot_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('pre-registration/', pre_registration, name="pre-registration"),
    path('complete-registration/', complete_registration, name="complete-registration"),
    path('faculty-options/', get_faculty_options, name="get-faculty-options"),
    path('department-options/', get_department_options, name="get-department-options"),
    path('verify-email/', verify_email, name="verify-email"),
    path('pre-forgot-password/', pre_forgot_password, name="pre-forgot-password"),
    path('forgot-password/', forgot_password, name="forgot_password"),
    path('student/', include(('student.urls', 'student'), namespace="student")),
    path('tutor/', include(('tutor.urls', 'tutor'), namespace="tutor")),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, profile, complete_profile, edit_profile, tutorial_sessions

urlpatterns = [
    path('home/', home, name="home"),
    path('complete-profile/', complete_profile, name="complete-profile"),
    path('edit-profile/', edit_profile, name="edit-profile"),
    path('profile/', profile, name="profile"),
    path('tutorial_sessions/', tutorial_sessions, name="tutorial_sessions")
]

tutor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (home, profile, complete_profile, edit_profile, 
                    my_courses, application_status, add_tutorial_session)

urlpatterns = [
    path('home/', home, name="home"),
    path('complete-profile/', complete_profile, name="complete-profile"),
    path('edit-profile/', edit_profile, name="edit-profile"),
    path('profile/', profile, name="profile"),
    # path('schedule-a-tutorial/', schedule_a_tutorial, name="schedule-a-tutorial"),
    path('my-courses/', my_courses, name="my-courses"),
    path('add-tutorial-session/', add_tutorial_session),
    path('application-status/', application_status, name="application-status")
]

student/models.py
# django related imports
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.dispatch import receiver

# app related imports
from mainapp.models import Institution, Faculty, Department

# system related imports 
from datetime import datetime
import os

def user_directory_path(instance, filename):
    date = datetime.now()
    print("Hello world. Just testing here", "******************")
    return "student/user_{0}/{1}/{2}/{3}/{4}".format(instance.user.id, date.strftime('%Y'), date.strftime('%m'), date.strftime('%d'), filename)

# Create your models here.
class TemporaryStudentRegistration(models.Model):
    email = models.EmailField()
    secret_token = models.CharField(max_length=124)

class Student(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT)
    courses = ArrayField(models.CharField(max_length=20), null=True)
    faculty = models.ForeignKey(Faculty, on_delete=models.PROTECT)
    department = models.ForeignKey(Department, on_delete=models.PROTECT)
    referral_code = models.CharField(max_length=12)
    points = models.BigIntegerField(default=0)
    tel = models.CharField(max_length=30)
    profile_pic = models.ImageField(upload_to=user_directory_path, null=True)

    def __str__(self):
        return self.first_name + self.last_name

@receiver(models.signals.post_delete, sender=Student)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    # remove the file from the file system with os.remove
    # if the file is in the file system 
    if instance.profile_pic:
        if os.path.isfile(instance.profile_pic.path):
            os.remove(instance.profile_pic.path)

@receiver(models.signals.pre_save, sender=Student)
def auto_delete_on_pre_save(sender, instance, **kwargs):
    # check to see the instance already exists in the db
    # compare the old file to the incoming file if they are thesame
    # delete if they are not
    print("I am here")
    if not instance.pk:
        return False
    try:
        old_file = Student.objects.get(pk=instance.pk).profile_pic
        print("I got the old file")
    except Student.DoesNotExist as e:
        print(e)
        return False
    
    new_file = instance.profile_pic
    print("I got the new file")
    if not new_file == old_file:
        print("Old file and new file are not equal")
        if os.path.isfile(old_file.path):
            print("Old file is a file")
            os.remove(old_file.path)
            print("Removed from file system")
    else:
        print(
            "Old and file and new file are equal"
        )

student/views.py
# django related imports
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required

# app related imports
from student.models import Student
from mainapp.models import Institution, Faculty, Department, User
from tutor.models import TutorialSession
from mainapp.views import generate_referral_code, category_check_factory_dectorator

#system related imports 
import math
import random

def profile_completion_redirect(func):
    # use this function as decorator to
    # redirect to complete profile or not based on if the 
    # his student entry has been recorded
    def inner(*args, **kwargs):
        if Student.objects.filter(user=args[0].user).exists():
            httpResponse = func(*args, **kwargs)
            return httpResponse
        else: 
            return HttpResponseRedirect(reverse('student:complete-profile'))
    return inner

@login_required
@category_check_factory_dectorator('student')
@profile_completion_redirect
def home(request):
    # if prompt_profile_completion(request.user):
    #     return HttpResponseRedirect(reverse('student:complete-profile'))
    student = Student.objects.filter(user = request.user)[0]
    context = {
        "user": request.user,
        "student": student
    }

    return render(request, 'dashboard/student-base.html', context)
    # return HttpResponse("Welcome new student")

@login_required
@category_check_factory_dectorator('student')
def complete_profile(request):
    institutions = Institution.objects.all()

    context = {
        "user": request.user,
        "institutions": institutions
    }

    if request.method == "POST":
        user = User.objects.filter(email=request.user)
        Student(
            user = request.user,
            first_name = request.POST["first_name"],
            last_name = request.POST["last_name"],
            institution_id = request.POST["institution"],
            faculty_id = request.POST["faculty"],
            department_id = request.POST["department"],
            profile_pic = request.FILES.get("profile_pic", None),
            tel = request.POST["tel"],
            referral_code = generate_referral_code("S")
        ).save()
        print('saved student')
    return render(request, 'student/complete-profile.html', context)

@profile_completion_redirect
@login_required
def profile(request):
    student = Student.objects.get(user=request.user)
    context = {
        "user": request.user,
        "student": student
    }
    return render(request, 'student/profile.html', context)

@category_check_factory_dectorator('student')
@profile_completion_redirect
@login_required
def edit_profile(request):
    if request.method == "POST":
        filename = None
        if request.FILES["profile-pic"]:
            fs = FileSystemStorage()
            file = request.FILES["profile-pic"]
            filename = fs.save(file.name, file)
            
        Student.objects.filter(user=request.user).update(
            first_name = request.POST["first_name"],
            last_name = request.POST["last_name"],
            institution_id = request.POST["institution"],
            faculty_id = request.POST["faculty"],
            department_id = request.POST["department"],
            tel = request.POST["tel"],
            referral_code = generate_referral_code("S"),
            profile_pic = filename
        )
        return HttpResponseRedirect(reverse('student:profile'))

    student = Student.objects.get(user=request.user)
    institutions = Institution.objects.all()
    faculties = Faculty.objects.all()
    departments = Department.objects.all()
    context = {
        "user" : request.user,
        "student" : student,
        "institutions" : institutions,
        "faculties" : faculties,
        "departments" : departments
    }
    
    return render(request, 'student/edit-profile.html', context)

@category_check_factory_dectorator('student')
@profile_completion_redirect
@login_required
def tutorial_sessions(request):
    student = Student.objects.get(user=request.user)
    tutorials = TutorialSession.objects.all()
    print(tutorials)
    context = {
        'student': student,
        'tutorials': tutorials
    }
    return render(request, 'student/tutorial-sessions.html', context)
    

student/templates/student/complete-profile.html
{% extends 'dashboard/student-base.html' %}
{% load static from static %}
{% block page_content %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <!-- <div class="page-title">
                <div class="title_left">
                    <h3>Form Validation</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Student Profile <small></small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <!-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a</li> -->
                                <!-- <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a></li>
                                        <li><a href="#">Settings 2</a></li>
                                    </ul>
                                </li> -->
                                <!-- <li><a class="close-link"><i class="fa fa-close"></i></a></li> -->
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="x_content bs-example-popovers">
                                <div class="alert alert-success alert-dismissible fade in" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                                    </button>
                                    <strong>Hi</strong>! 👋 Welcome. You made a great choice joining <b>MyTutz</b> 😊. Please complete your profile to get started
                                </div>
                            </div>
                            <form method="POST" class="form-horizontal form-label-left" data-parsley-validate>
                                <!-- <p>For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a></p>
                                <span class="section">Personal Info</span> -->
                                <!-- <div class="item form-group">
                                    <p style="text-align: right" class="col-md-3 col-sm-3 col-xs-12">Referral Code</p>
                                    <p class="col-md-6 col-sm-6 col-xs-12">
                                        68982729 <span>   (Refer and gain <a href="#"><b>Points</b></a>)</span>
                                    </p>
                                </div> -->
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">First Name <span class="required">*</span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="first_name" class="form-control col-md-7 col-xs-12" maxlength="100" data-validate-length-range="6" data-validate-words="2" name="first_name" placeholder="" required="required" type="text">
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Last Name <span class="required">*</span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="last_name" class="form-control col-md-7 col-xs-12" maxlength="100" data-validate-length-range="6" data-validate-words="2" name="last_name" placeholder="" required="required" type="text" required>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="profile_pic">Profile Picture</label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="file" name="profile_pic" class="form-control col-md-7 col-xs-12" id="profile_pic">
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">Phone <span class="required">*</span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="number" id="tel" name="tel" required="required" data-validate-minmax="10,100" class="form-control col-md-7 col-xs-12" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Institution <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select id="institution" name="institution" class="select2_group form-control" required>
                                        {% for institution in institutions %}
                                            <option value="{{institution.id}}">{{institution.name}}</option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Faculty <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select id="faculty" name="faculty" class="select2_group form-control" required>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <select id="department" name="department" class="select2_group form-control" required>
                                        </select>
                                    </div>
                                </div>
                                <!-- <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" data-tagsinput-init="true" style="display: none;"><div id="tags_1_tagsinput" class="tagsinput" style="width: auto; min-height: 100px; height: 100px;"><span class="tag"><span>social&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>adverts&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>sales&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>icons&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><div id="tags_1_addTag"><input id="tags_1_tag" value="" data-default="add a tag" style="color: rgb(102, 102, 102); width: 72px;"></div><div class="tags_clear"></div></div>
                                        <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                                    </div>
                                </div> -->
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-md-offset-3">
                                        <!-- <button type="submit" class="btn btn-primary">Cancel</button> -->
                                        {% csrf_token %}
                                        <button id="send" type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock page_content %}

{% block js %}
    <script src="{% static 'dashboard/js/student/complete-profile.js' %}"></script>
{% endblock %}

student/templates/student/my-courses.html
{% extends 'dashboard/student-base.html' %}
{% load static from static %}
{% block page_content %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <!-- <div class="page-title">
                <div class="title_left">
                    <h3>Form Validation</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Update Courses<small></small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <!-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a</li> -->
                                <!-- <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a></li>
                                        <li><a href="#">Settings 2</a></li>
                                    </ul>
                                </li> -->
                                <!-- <li><a class="close-link"><i class="fa fa-close"></i></a></li> -->
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-6">
                                    <div class="chips chips-placeholder"></div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock page_content %}

student/templates/student/profile.html
{% extends 'dashboard/student-base.html' %}
{% block page_content %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <!-- <div class="page-title">
                <div class="title_left">
                    <h3>Form Validation</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Your Profile <small></small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <!-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a</li> -->
                                <!-- <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settiangs 1</a></li>
                                        <li><a href="#">Settings 2</a></li>
                                    </ul>
                                </li> -->
                                <li><a href="{% url 'student:edit-profile' %}" class="edit-profile"><i class="fa fa-edit fa-2x"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <form class="form-horizontal form-label-left" novalidate>
                                <!-- <p>For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a></p>
                                <span class="section">Personal Info</span> -->
                                <div class="item form-group">
                                    <p style="text-align: right" class="col-md-3 col-sm-3 col-xs-12">Referral Code</p>
                                    <p class="col-md-6 col-sm-6 col-xs-12">
                                        <b>{{student.referral_code}}</b> <span>   (Refer and gain <a href="#"><b>Points</b></a>)</span>
                                    </p>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">First Name <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" value="{{student.first_name}}" type="text" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Last Name <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" value="{{student.last_name}}" type="text" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="email" id="email" name="email" value="{{user.email}}" class="form-control col-md-7 col-xs-12" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">Phone <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="number" id="number" name="number" value="{{student.tel}}" data-validate-minmax="10,100" class="form-control col-md-7 col-xs-12" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Institution <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{student.institution.name}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Faculty <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{student.faculty.name}}" readonly>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{student.department.name}}" readonly>
                                    </div>
                                </div>
                                <!-- <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" data-tagsinput-init="true" style="display: none;"><div id="tags_1_tagsinput" class="tagsinput" style="width: auto; min-height: 100px; height: 100px;"><span class="tag"><span>social&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>adverts&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>sales&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>icons&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><div id="tags_1_addTag"><input id="tags_1_tag" value="" data-default="add a tag" style="color: rgb(102, 102, 102); width: 72px;"></div><div class="tags_clear"></div></div>
                                        <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                                    </div>
                                </div> -->
                                <div class="ln_solid"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock page_content %}