mytutz/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.views import homepage, pre_registration, complete_registration, verify_email, user_login, user_logout, \
                            get_faculty_options, get_department_options, pre_forgot_password, forgot_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name="home"),
    path('pre-registration/', pre_registration, name="pre-registration"),
    path('complete-registration/', complete_registration, name="complete-registration"),
    path('faculty-options/', get_faculty_options, name="get-faculty-options"),
    path('department-options/', get_department_options, name="get-department-options"),
    path('verify-email/', verify_email, name="verify-email"),
    path('pre-forgot-password/', pre_forgot_password, name="pre-forgot-password"),
    path('forgot-password/', forgot_password, name="forgot_password"),
    path('student/', include(('student.urls', 'student'), namespace="student")),
    path('tutor/', include(('tutor.urls', 'tutor'), namespace="tutor")),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (home, profile, complete_profile, edit_profile, 
                    my_courses, application_status, add_tutorial_session)

urlpatterns = [
    path('home/', home, name="home"),
    path('complete-profile/', complete_profile, name="complete-profile"),
    path('edit-profile/', edit_profile, name="edit-profile"),
    path('profile/', profile, name="profile"),
    # path('schedule-a-tutorial/', schedule_a_tutorial, name="schedule-a-tutorial"),
    path('my-courses/', my_courses, name="my-courses"),
    path('add-tutorial-session/', add_tutorial_session),
    path('application-status/', application_status, name="application-status")
]

tutor/models.py
# django related imports
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.dispatch import receiver

# app related imports
from mainapp.models import Institution, Faculty, Department, Course
from student.models import Student

# system related imports 
from datetime import datetime
import os

application_status = [
    ["pending", "pending"],
    ["approved", "approved"],
    ["refused", "refused"]
]

def user_directory_path(instance, filename):
    date = datetime.now()
    print("Hello world. Just testing here", "******************")
    return "tutor/user_{0}/{1}/{2}/{3}/{4}".format(instance.user.id, date.strftime('%Y'), date.strftime('%m'), date.strftime('%d'), filename)

# Create your models here
class TemporaryTutorRegistration(models.Model):
    email = models.EmailField()
    secret_token = models.CharField(max_length=124)

class AcademicQualification(models.Model):
    title = models.CharField(max_length=30);

    def __str__(self):
        return self.title

class Tutor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT)
    referral_code = models.CharField(max_length=12)
    points = models.BigIntegerField(default=0)
    tel = models.CharField(max_length=30)
    application_status = models.CharField(choices=application_status, max_length=50, default="pending")
    academic_qualification = models.ForeignKey(AcademicQualification, on_delete=models.PROTECT)
    profile_pic = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    transcript = models.FileField(upload_to=user_directory_path, null=True)
    cv = models.FileField(upload_to=user_directory_path, null=True)
    application_viewed = models.BooleanField(default=False)     # this will be set to true when the application_status has been updated

    def __str__(self):
        return self.first_name + " " + self.last_name

class TutorCourse(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    tutor = models.ForeignKey(Tutor, on_delete=models.PROTECT)

    def __str__(self):
        return self.tutor.first_name + " " + self.tutor.last_name + "  -  " + self.course.title

class TutorAccount(models.Model):
    tutor = models.OneToOneField(Tutor, on_delete=models.CASCADE)
    balance = models.BigIntegerField(default=0)

class TutorialLocation(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class TutorialSession(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.PROTECT)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    cover_image = models.ImageField(upload_to=user_directory_path, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    tutorial_date = models.DateField()
    from_time = models.TimeField()
    to_time = models.TimeField()
    description = models.TextField(null=True)
    cost = models.BigIntegerField()
    location = models.ForeignKey(TutorialLocation, on_delete=models.PROTECT)


class BookedTutorialSession(models.Model):
    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    tutorial_session = models.ForeignKey(TutorialSession, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.student.first_name + " booked for " + self.tutorial_session.course.title

@receiver(models.signals.post_delete, sender=Tutor)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    # remove the file from the file system with os.remove
    # if the file is in the file system 
    if instance.profile_pic:
        if os.path.isfile(instance.profile_pic.path):
            os.remove(instance.profile_pic.path)
    if instance.transcript:
        if os.path.isfile(instance.transcript.path):
            print(instance.transcript.path)
            os.remove(instance.transcript.path)
    if instance.cv:
        if os.path.isfile(instance.cv.path):
            os.remove(instance.cv.path)

@receiver(models.signals.pre_save, sender=Tutor)
def auto_delete_on_pre_save(sender, instance, **kwargs):
    # check to see the instance already exists in the db
    # compare the old file to the incoming file if they are thesame
    # delete if they are not
    print("I am here")
    if not instance.pk:
        return False
    try:
        old_file1 = Tutor.objects.get(pk=instance.pk).profile_pic
        old_file2 = Tutor.objects.get(pk=instance.pk).transcript
        old_file3 = Tutor.objects.get(pk=instance.pk).cv
        print("I got the old file")
    except Tutor.DoesNotExist as e:
        print(e)
        return False
    
    new_file1 = instance.profile_pic
    new_file2 = instance.transcript
    new_file3 = instance.cv
    print("I got the new file")
    if not new_file1 != old_file1:
        print("Old file and new file are not equal **** ", old_file1)
        if old_file1 and os.path.isfile(old_file1.path):
            print("Old file is a file")
            os.remove(old_file1.path)
            print("Removed from file system")
    else:
        print("Old and file and new file are equal")
    if not new_file2 != old_file2:
        print("Old file and new file are not equal")
        if os.path.isfile(old_file2.path):
            print("Old file is a file")
            os.remove(old_file2.path)
            print("Removed from file system")
    else:
        print("Old and file and new file are equal")
    if not new_file3 != old_file3:
        print("Old file and new file are not equal")
        if os.path.isfile(old_file3.path):
            print("Old file is a file")
            os.remove(old_file3.path)
            print("Removed from file system")
    else:
        print("Old and file and new file are equal")

tutor/views.py
# django related imports
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse

# app related imports
from .models import Tutor, AcademicQualification, TutorCourse, TutorialLocation, TutorialSession, BookedTutorialSession
from mainapp.models import Institution, Faculty, Department, User, Course
from mainapp.views import generate_referral_code, category_check_factory_dectorator, tutor_application_redirect

#system related imports 
import math
import random


# Create your views here.
def profile_completion_redirect(func):
    # use this function as decorator to
    # redirect to complete profile or not based on if the 
    # his student entry has been recorded
    def inner(*args, **kwargs):
        if Tutor.objects.filter(user=args[0].user).exists():
            httpResponse = func(*args, **kwargs)
            return httpResponse
        else: 
            return HttpResponseRedirect(reverse('tutor:complete-profile'))
    return inner


@login_required
@profile_completion_redirect
@category_check_factory_dectorator('tutor')
@tutor_application_redirect
def home(request):
    # if prompt_profile_completion(request.user):
    #     return HttpResponseRedirect(reverse('student:complete-profile'))
    tutor = Tutor.objects.filter(user = request.user)[0]
    context = {
        "user": request.user,
        "tutor": tutor
    }

    return render(request, 'dashboard/tutor-base.html', context)

@category_check_factory_dectorator('tutor')
@login_required
def complete_profile(request):
    print(request.POST)
    institutions = Institution.objects.all()
    courses = Course.objects.all();
    qualifications = AcademicQualification.objects.all();
    context = {
        "user": request.user,
        "institutions": institutions,
        "courses": courses,
        "qualifications": qualifications
    }

    if request.method == "POST":
        user = User.objects.filter(email=request.user)
        courses = [course.strip() for course in request.POST["courses"].split(",") if course.strip() != ""]
        
        academic_qualification = AcademicQualification.objects.filter(id=request.POST["qualification"])[0]
        print("academic qualification is ", academic_qualification)
        print("request files is ", request.FILES)
        tutor = Tutor(
                    user = request.user,
                    first_name = request.POST["first_name"],
                    last_name = request.POST["last_name"],
                    institution_id = request.POST["institution"],
                    tel = request.POST["tel"],
                    referral_code = generate_referral_code("T"),
                    profile_pic = request.FILES.get("profile_pic", None),
                    academic_qualification = academic_qualification,
                    transcript = request.FILES.get("transcript", None),
                    cv = request.FILES.get("cv", None)
                )
        tutor.save()
        print("tutor is ", tutor)
        for course in courses:
            TutorCourse(
                course = Course.objects.filter(id=course)[0],
                tutor = tutor
            ).save()

        return HttpResponseRedirect(reverse('tutor:application-status'))
    return render(request, 'tutor/complete-profile.html', context)

@category_check_factory_dectorator('tutor')
@profile_completion_redirect
@tutor_application_redirect
@login_required
def profile(request):
    tutor = Tutor.objects.get(user=request.user)
    context = {
        "user": request.user,
        "tutor": tutor
    }
    return render(request, 'tutor/profile.html', context)

@category_check_factory_dectorator('tutor')
@profile_completion_redirect
@tutor_application_redirect
@login_required
def edit_profile(request):
    if request.method == "POST":
        fs = FileSystemStorage()
        file = request.FILES["profile-pic"]
        profile_pic = fs.save(file.name, file)
        # file = request.FILES["transcript"]
        # transcript = fs.save(file.name, file)
        # file = request.FILES["cv"]
        # cv = fs.save(file.name, file)
            
        Tutor.objects.filter(user=request.user).update(
            first_name = request.POST["first_name"],
            last_name = request.POST["last_name"],
            # institution_id = request.POST["institution"],
            tel = request.POST["tel"],
            # referral_code = generate_referral_code("S"),
            profile_pic = profile_pic,
            # courses = courses,
            # qualification = request.POST["qualification"],
            # transcript = transcript,
            # cv = request.FILES["cv"]
        )
        return HttpResponseRedirect(reverse('tutor:profile'))

    tutor = Tutor.objects.get(user=request.user)
    institutions = Institution.objects.all()
    faculties = Faculty.objects.all()
    departments = Department.objects.all()
    print(tutor.profile_pic.url, "*********")
    context = {
        "user" : request.user,
        "tutor" : tutor,
        "institutions" : institutions,
        "faculties" : faculties,
        "departments" : departments
    }
    
    return render(request, 'tutor/edit-profile.html', context)

def application_status(request):
    tutor = Tutor.objects.get(user=request.user)
    context = {
        "application_status" : tutor.application_status,
        "tutor" : tutor
    }
    # print(tutor.profile_pic.url)
    if tutor.application_status == "pending": context["text_color"] = "text-primary"
    if tutor.application_status == "denied":  context["text-color"] = "text-danger" 
    if tutor.application_status == "success": context["text-color"] = "text-success"

    return render(request, "tutor/application-status-msg.html", context)

@category_check_factory_dectorator('tutor')
@profile_completion_redirect
@tutor_application_redirect
@login_required
def my_courses(request):
    tutor = Tutor.objects.get(user=request.user)
    tutor_courses = TutorCourse.objects.filter(tutor=tutor)
    locations = TutorialLocation.objects.all()
    tutorial_sessions = TutorialSession.objects.filter(tutor=tutor)
    sessions = []
    for index, tutorial_session in enumerate(tutorial_sessions.iterator()):
        booked = BookedTutorialSession.objects.filter(tutorial_session=tutorial_session)
        number_of_students = booked.count()
        # if booked:
        #     number_of_students = booked.count()
        # else:
        #     number_of_students = 0
        print(tutorial_session)
        tutorial_session.number_of_students = number_of_students
        sessions.append(tutorial_session)

    context = {
        "tutor": tutor,
        "tutor_courses": tutor_courses,
        "locations": locations,
        "tutorial_sessions": sessions
    }

    return render(request, 'tutor/my-courses.html', context)

def add_tutorial_session(request):
    if request.method == "POST":
        print(request.POST)
        tutor = Tutor.objects.get(user=request.user)
        
        tutorial_session = TutorialSession(
            tutor = tutor,
            course = Course.objects.filter(id=request.POST["course"])[0],
            cover_image = request.FILES.get("cover-image", None),
            tutorial_date = request.POST["date"],
            from_time = request.POST["time-from"],
            to_time = request.POST["time-to"],
            description = request.POST["description"],
            cost = request.POST["cost"],
            location = TutorialLocation.objects.filter(id=request.POST["location"])[0]
        )

        number_of_students = BookedTutorialSession.objects.filter(tutorial_session=tutorial_session).count()
        tutorial_session.number_of_students = number_of_students
        tutorial_session.save()
        context = {
            "tutorial_session": tutorial_session
        }
        return TemplateResponse(request, "tutor/session-template.html", context)

tutor/templates/tutor/application-status-msg.html
{% extends 'dashboard/tutor-base.html' %}
{% load static from static %}
{% block page_content %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Application Status: <small class="{{text_color}}">{{application_status|upper}}</small></h2>
                            <div class="clearfix"></div>
                        </div>
                        <div>
                            {% if application_status == "pending" %}
                            <p><b>Thanks for your interest in becoming a tutor at MyTutz. You would be notified via mail
                                once the status of your application has changed</b>
                            </p>
                            {% endif %}
                            {% if application_status == "denied" %}
                            <p><b>Thanks for your interest in becoming a MyTutz tutor, but we are sorry at this time we
                                have decided not to move forward with your application. 
                                You can edit your profile again and re-submit in <span class="text-danger">6months</span></b>
                            </p>
                            {% endif %}
                            {% if application_status == "success" %}
                            <p><b>Dear Sir, We have decided to move forward with you becoming a MyTutz tutor.</b></p>
                            <button class="btn btn-success">Continue</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tutor/templates/tutor/profile.html
{% extends 'dashboard/tutor-base.html' %}
{% block page_content %}
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <!-- <div class="page-title">
                <div class="title_left">
                    <h3>Form Validation</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Your Profile <small></small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <!-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a</li> -->
                                <!-- <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settiangs 1</a></li>
                                        <li><a href="#">Settings 2</a></li>
                                    </ul>
                                </li> -->
                                <li><a href="{% url 'tutor:edit-profile' %}" class="edit-profile"><i class="fa fa-edit fa-2x"></i></a></li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <form class="form-horizontal form-label-left" novalidate>
                                <!-- <p>For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a></p>
                                <span class="section">Personal Info</span> -->
                                <div class="item form-group">
                                    <p style="text-align: right" class="col-md-3 col-sm-3 col-xs-12">Referral Code</p>
                                    <p class="col-md-6 col-sm-6 col-xs-12">
                                        <b>{{tutor.referral_code}}</b> <span>   (Refer and gain <a href="#"><b>Points</b></a>)</span>
                                    </p>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">First Name <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" value="{{tutor.first_name}}" type="text" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Last Name <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="name" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" value="{{tutor.last_name}}" type="text" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="email" id="email" name="email" value="{{user.email}}" class="form-control col-md-7 col-xs-12" readonly>
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">Phone <span class="required"></span></label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="number" id="number" name="number" value="{{tutor.tel}}" data-validate-minmax="10,100" class="form-control col-md-7 col-xs-12" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Institution <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{tutor.institution.name}}" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Faculty <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{tutor.faculty.name}}" readonly>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required"></span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" class="form-control col-md-7 col-xs-12" value="{{tutor.department.name}}" readonly>
                                    </div>
                                </div>
                                <!-- <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">Department <span class="required">*</span> </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="tags_1" type="text" class="tags form-control" value="social, adverts, sales" data-tagsinput-init="true" style="display: none;"><div id="tags_1_tagsinput" class="tagsinput" style="width: auto; min-height: 100px; height: 100px;"><span class="tag"><span>social&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>adverts&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>sales&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><span class="tag"><span>icons&nbsp;&nbsp;</span><a href="#" title="Removing tag">x</a></span><div id="tags_1_addTag"><input id="tags_1_tag" value="" data-default="add a tag" style="color: rgb(102, 102, 102); width: 72px;"></div><div class="tags_clear"></div></div>
                                        <div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>
                                    </div>
                                </div> -->
                                <div class="ln_solid"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
{% endblock page_content %}

tutor/templates/tutor/session-template.html
{% load static from static %}

<div class="col-md-3 col-xs-12 widget widget_tally_box">
    <div class="x_panel fixed_height_390">
        <div class="x_content">
            <div class="flex">
                <ul class="list-inline widget_profile_box">
                    <li>
                        <i class="fas fa-pencil-alt"></i>
                    </li>
                    <li>
                        {% if tutorial_session.cover_image %}
                            <img src="{{tutorial_session.cover_image}}" alt="Tutorial cover" class="img-circle profile_img">
                        {% else %}
                            <img src="{% static 'images/default-tutorial-session-cover.jpg' %}" alt="default tutorial session cover" class="img-circle profile_img">
                        {% endif %}
                    </li>
                    <li>
                        
                    </li>
                </ul>
            </div>

            <h3 class="name">{{tutorial_session.course.code}}</h3>

            <div class="flex">
                <ul class="list-inline count2">
                    <li>
                        <h5>{{tutorial_session.from_time}}</h5>
                        <span>Start Time</span>
                    </li>
                    <li>
                        <h3>{{tutorial_session.number_of_students}}</h3>
                        <span>Registered Students</span>
                    </li>
                    <li>
                        <h5>{{tutorial_session.to_time}}</h5>
                        <span>End Time</span>
                    </li>
                </ul>
            </div>
            <p><b>{{tutorial_session.location}}</b></p>
            <p>
                {{tutorial_session.description}}
            </p>
        </div>
    </div>
</div>